"""
part 1:
- each antenna has a specific frequency indicated by a single lowercase/uppercase letter, digit.
    => "A", "a", "0"
    => "a" and "A" are different frequencies
- signal only applies to antinodes that are perfectly in line with two antennas of the same frequency
    - only antenna has to be twice as far away from the other
- any pair on antennas with the same frequency has two antinodes, one on either side of them
- antennas with different frequencies don't create antinodes

e.g.
2 antennas with 2 antinodes:
..........
...#......
..........
....a.....
..........
.....a....
..........
......#...
..........
..........

- frequency: "a"
- two antinodes: "#"

3 antennas with 4 antinodes:
..........
...#......
#.........
....a.....
........a.
.....a....
..#.......
......#...
..........
..........

- only two valid antinodes, because they are not perfectly aligned
"""

"""
frequencies and antennas have to have the same distance between each other
"""


def part1(input_data):
    solution = 0
    return solution


def part2(input_data):
    solution = 0
    return solution


if __name__ == "__main__":
    with open("./inputs/day08_sample.txt") as f:
        data = f.read().strip().split("\n")
    print("Part 1:", part1(data))
    print("Part 2:", part2(data))
